version: "3.8"

services:
  database:
    image: postgres:15
    container_name: strapi_postgres
    restart: always
    environment:
      POSTGRES_DB: strapi_db
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  strapi:
    build: .
    container_name: strapi_app
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_password
      NODE_ENV: production
    ports:
      - "1337:1337"
    volumes:
      - ./public/uploads:/app/public/uploads

volumes:
  postgres_data:
